// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.monkey.outjava;

public final class Person {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_person_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_person_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014person.proto\"3\n\006person\022\r\n\005query\030\001 \001(\t\022" +
                        "\013\n\003age\030\002 \001(\005\022\r\n\005money\030\003 \001(\001B\034\n\022com.monke" +
                        "y.outjavaB\006Personb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_person_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_person_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_person_descriptor,
                new java.lang.String[]{"Query", "Age", "Money",});
    }

    private Person() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface personOrBuilder extends
            // @@protoc_insertion_point(interface_extends:person)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 类型，字段，长度
         * </pre>
         * <p/>
         * <code>string query = 1;</code>
         */
        java.lang.String getQuery();

        /**
         * <pre>
         * 类型，字段，长度
         * </pre>
         * <p/>
         * <code>string query = 1;</code>
         */
        com.google.protobuf.ByteString
        getQueryBytes();

        /**
         * <code>int32 age = 2;</code>
         */
        int getAge();

        /**
         * <code>double money = 3;</code>
         */
        double getMoney();
    }

    /**
     * Protobuf type {@code person}
     */
    public static final class person extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:person)
            personOrBuilder {
        public static final int QUERY_FIELD_NUMBER = 1;
        public static final int AGE_FIELD_NUMBER = 2;
        public static final int MONEY_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:person)
        private static final com.monkey.outjava.Person.person DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<person>
                PARSER = new com.google.protobuf.AbstractParser<person>() {
            public person parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new person(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.monkey.outjava.Person.person();
        }

        private volatile java.lang.Object query_;
        private int age_;
        private double money_;
        private byte memoizedIsInitialized = -1;

        // Use person.newBuilder() to construct.
        private person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private person() {
            query_ = "";
            age_ = 0;
            money_ = 0D;
        }

        private person(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            query_ = s;
                            break;
                        }
                        case 16: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 25: {

                            money_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.monkey.outjava.Person.internal_static_person_descriptor;
        }

        public static com.monkey.outjava.Person.person parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.monkey.outjava.Person.person parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.monkey.outjava.Person.person parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.monkey.outjava.Person.person parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.monkey.outjava.Person.person parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.monkey.outjava.Person.person parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.monkey.outjava.Person.person prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.monkey.outjava.Person.person getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<person> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.monkey.outjava.Person.internal_static_person_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.monkey.outjava.Person.person.class, com.monkey.outjava.Person.person.Builder.class);
        }

        /**
         * <pre>
         * 类型，字段，长度
         * </pre>
         * <p/>
         * <code>string query = 1;</code>
         */
        public java.lang.String getQuery() {
            java.lang.Object ref = query_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                query_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 类型，字段，长度
         * </pre>
         * <p/>
         * <code>string query = 1;</code>
         */
        public com.google.protobuf.ByteString
        getQueryBytes() {
            java.lang.Object ref = query_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                query_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 age = 2;</code>
         */
        public int getAge() {
            return age_;
        }

        /**
         * <code>double money = 3;</code>
         */
        public double getMoney() {
            return money_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getQueryBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
            }
            if (age_ != 0) {
                output.writeInt32(2, age_);
            }
            if (money_ != 0D) {
                output.writeDouble(3, money_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getQueryBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (money_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, money_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.monkey.outjava.Person.person)) {
                return super.equals(obj);
            }
            com.monkey.outjava.Person.person other = (com.monkey.outjava.Person.person) obj;

            boolean result = true;
            result = result && getQuery()
                    .equals(other.getQuery());
            result = result && (getAge()
                    == other.getAge());
            result = result && (
                    java.lang.Double.doubleToLongBits(getMoney())
                            == java.lang.Double.doubleToLongBits(
                            other.getMoney()));
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + QUERY_FIELD_NUMBER;
            hash = (53 * hash) + getQuery().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (37 * hash) + MONEY_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getMoney()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<person> getParserForType() {
            return PARSER;
        }

        public com.monkey.outjava.Person.person getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code person}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:person)
                com.monkey.outjava.Person.personOrBuilder {
            private java.lang.Object query_ = "";
            private int age_;
            private double money_;

            // Construct using com.monkey.outjava.Person.person.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.monkey.outjava.Person.internal_static_person_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.monkey.outjava.Person.internal_static_person_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.monkey.outjava.Person.person.class, com.monkey.outjava.Person.person.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                query_ = "";

                age_ = 0;

                money_ = 0D;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.monkey.outjava.Person.internal_static_person_descriptor;
            }

            public com.monkey.outjava.Person.person getDefaultInstanceForType() {
                return com.monkey.outjava.Person.person.getDefaultInstance();
            }

            public com.monkey.outjava.Person.person build() {
                com.monkey.outjava.Person.person result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.monkey.outjava.Person.person buildPartial() {
                com.monkey.outjava.Person.person result = new com.monkey.outjava.Person.person(this);
                result.query_ = query_;
                result.age_ = age_;
                result.money_ = money_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.monkey.outjava.Person.person) {
                    return mergeFrom((com.monkey.outjava.Person.person) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.monkey.outjava.Person.person other) {
                if (other == com.monkey.outjava.Person.person.getDefaultInstance())
                    return this;
                if (!other.getQuery().isEmpty()) {
                    query_ = other.query_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (other.getMoney() != 0D) {
                    setMoney(other.getMoney());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.monkey.outjava.Person.person parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.monkey.outjava.Person.person) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <pre>
             * 类型，字段，长度
             * </pre>
             * <p/>
             * <code>string query = 1;</code>
             */
            public java.lang.String getQuery() {
                java.lang.Object ref = query_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    query_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 类型，字段，长度
             * </pre>
             * <p/>
             * <code>string query = 1;</code>
             */
            public Builder setQuery(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                query_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 类型，字段，长度
             * </pre>
             * <p/>
             * <code>string query = 1;</code>
             */
            public com.google.protobuf.ByteString
            getQueryBytes() {
                java.lang.Object ref = query_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    query_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 类型，字段，长度
             * </pre>
             * <p/>
             * <code>string query = 1;</code>
             */
            public Builder setQueryBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                query_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 类型，字段，长度
             * </pre>
             * <p/>
             * <code>string query = 1;</code>
             */
            public Builder clearQuery() {

                query_ = getDefaultInstance().getQuery();
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 2;</code>
             */
            public int getAge() {
                return age_;
            }

            /**
             * <code>int32 age = 2;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 2;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>double money = 3;</code>
             */
            public double getMoney() {
                return money_;
            }

            /**
             * <code>double money = 3;</code>
             */
            public Builder setMoney(double value) {

                money_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double money = 3;</code>
             */
            public Builder clearMoney() {

                money_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:person)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
